language: julia
os:
  - linux
  - osx
julia:
  - release
  - nightly
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("DataFrames");'
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'Pkg.test("DataFrames", coverage=true)'; else julia -e 'Pkg.test("DataFrames")'; fi
after_success:
  - if [ $TRAVIS_JULIA_VERSION = "nightly" ]; then julia -e 'cd(Pkg.dir("DataFrames")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'; fi
